### ISSUE TITLE
Non-linear denoisers

### ISSUE THREAD

**Issue by Enable72** [rgavaska/Convergent-PnP#1]
Your paper says you have also replaced the NLM denoiser with non-linear TV and DnCNN denoisers. How should the code de updated then?

**Comment by rgavaska** [comment]
Generally speaking, you need to do 3 changes in demo_inpainting.m:
1) Replace line 34 by `W_nosym = @(x) denoise(x)` where `denoise` is whatever denoiser you wish to use.
2) Replace line 35 by `D = ones(rows,cols)` where `[rows,cols]` is the image size.
3) Replace line 37 by `objfun = []` and comment out the part at the end where `obj_vals` is plotted. This is because except for some special cases (such as linear NLM and TV denoisers), using an arbitrary denoiser does not correspond to any objective function.
